#!/bin/sh
# Build the documentation site into ./site.
#
# This is what Cloudflare Workers Builds runs, so it has to stand on its own in
# that image: Ubuntu with Python 3.13 and no uv. Installing uv rather than
# reaching for the preinstalled pip is deliberate — uv reads uv.lock, so the
# published site is generated by exactly the versions CI and a contributor's
# machine use, and it fetches the Python this project requires by itself.
set -eu

if ! command -v uv >/dev/null 2>&1; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
    PATH="$HOME/.local/bin:$PATH"
    export PATH
fi

uv run --group docs python scripts/build_multilingual_docs.py
